spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/dbcustomer
    username: user
    password: password
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
